version: '3.8'

services:
  postgres:
    image: postgres:latest  # Usando a imagem oficial do PostgreSQL
    container_name: meu-postgres-container  # Nome do container
    environment:
      POSTGRES_USER: postgres  # Nome do usuário do PostgreSQL
      POSTGRES_PASSWORD: postgres  # Senha do usuário
      POSTGRES_DB: musica  # Nome do banco de dados a ser criado
    ports:
      - "5433:5432"  # Mapeia a porta 5433 do container para a máquina local
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volume para persistir dados

volumes:
  postgres_data:  # Definindo o volume para persistência de dados
